
algo = scrypt_cpu
miningaddr = tf1q0v96qqntuz2rhefvp6gy4j27w4fc4ws4gl6vhd
coinbaseScript = 20:-1:27
testnet = true
pool = 207.180.234.16:35055
timeout = 10s
mineonce=true
retryMaxAttempts = 5
retryMaxBackoff = 30.0